the issue with bringing thrown errors and async togethers is telling errors from exceptions so the process can continue without a restart.