SoulRaven: if you throw() one, that goes through exception handling