because cb(err) is called immediately