cainus: it's very likely try/catch inside the test framework